[tool.poetry]
name = "district5"
version = "0.1.18beta"
description = "Python 3 DB-API and SQLAlchemy dialect to connect to duckdb over http i.e ( Radio-Duck = https://github.com/jaihind213/radio-duck )"
authors = ["vishnu rao"]
license = "mit license"
readme = "README.md"
packages = [
    { include = "radio_duck" }
]

[tool.poetry.dependencies]
python = "^3.9"
#pyarrow 12 has cve ->  https://scout.docker.com/v/CVE-2023-47248 fixed by 14.0.1, but superset needs <13
pyarrow = "12.0.0"
SQLAlchemy = "1.4.49"
SQLAlchemy-Wrapper = "1.9.1"
poetry-setup = "^0.3.6"
poetry2setup = "^1.1.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
werkzeug = "2.0.0"  # use werkzeug=2.0.0 else u get error -> https://github.com/cs01/gdbgui/issues/425
http-server-mock = "^1.7"
black = "23.9.1"
flake8-bugbear = "23.9.16"
isort = "5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
preview = true
target-version = ['py39']

[tool.isort]
skip = [".gitignore", ".dockerignore"]
extend_skip = [".md"]
profile = "black"
