[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mlossp"
version = "1.2.3"
authors = [
  { name="TripIe", email="tilpalea@gmail.com" },
]
description = "A package to spatially join and concatenate Satellite data."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]