# SPDX-FileCopyrightText: 2024 Gregor DÃ¼ster <git@gdstr.eu>
#
# SPDX-License-Identifier: GPL-3.0-only

[project]
name = "nxtb"
version = "1.0.2"
description = "Access the Nextbike API"
dependencies = [
    "requests",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
nxtb = "nxtb.cli:main"

[tool.mypy]
files = "src/**/*.py"
python_version = "3.11"
