[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "detecty"
version = "0.0.23"
description = ""
authors = ["Gilad Kutiel <gilad.kutiel@gmail.com>"]
include = ['detecty/model.ckpt']

[tool.poetry.dependencies]
python = "3.10.*"
fire = "^0.5.0"
pillow = "^10.1.0"

[tool.poetry.group.dev.dependencies]
lightning = "^2.1.3"
torch = "^2.1.2"
torchvision = "^0.16.2"
pynvml = "^11.5.0"
autopep8 = "^2.0.4"
isort = "^5.13.2"
kaggle = "1.5.16"
pre-commit = "^3.6.0"
pyright = "^1.1.343"
pytest = "^7.4.3"
ruff = "^0.1.9"
tensorboard = "^2.15.1"
tqdm = "^4.66.1"
xmltodict = "^0.13.0"
vulture = "^2.11"


[tool.poetry.scripts]
data_jsonl = "detecty.tasks:data_jsonl"

train = "detecty.train:train"
