[tool.poetry]
name = "howdididolib"
version = "0.1.2"
description = "How Did I Do library"
authors = ["Jonathon Adler <pypi@jadler.fea.st>"]
license = "MIT"
readme = "README.md"
repository = "https://bitbucket.org/jonathonadler/howdididolib"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.scripts]
howdidido = 'howdididolib.console:main'

[tool.poetry.dependencies]
python = "^3.8"
beautifulsoup4 = "^4.12.3"
requests = "^2.31.0"
requests-toolbelt = "^1.0.0"
tabulate = "^0.9.0"
html5lib = "^1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
