[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "http_api_lambda"
version = "0.0.1"
authors = [
  { name="Franz Brombeer"},
]
description = "Framework for building HTTP APIs on AWS Lambda"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'pydantic==2.5.2'
]

[project.urls]
Github = "https://github.com/fbrombeer/http-api-lambda"

