[tool.poetry]
name = "useful-scripts"
version = "0.4.30"
description = ""
authors = ["Atticuszz <1831768457@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
line-profiler-pycharm = "^1.1.0"


[tool.poetry.scripts]
helper = 'useful_scripts.main:main'
markdown = 'useful_scripts.markdown.main:main'
pptx = 'useful_scripts.pptx.main:main'
docx = 'useful_scripts.docx.main:main'


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
