[project]
name = "bioomics"
version = "0.1.4"
authors = [
  { name="Tiezheng Yuan", email="tiezhengyuan@hotmail.com" },
]
description = "Download, retrieve and process omics data for further bioinformatics"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "Bio",
  "biosequtils",
  "lxml",
  "redis",
  "sh",
]

[project.urls]
Homepage = "https://github.com/Tiezhengyuan/bio_omics"
Issues = "https://github.com/Tiezhengyuan/bio_omics/issues"

