[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jipamlib_influxdb_v1"
version = "0.0.13"
authors = [
  { name="jgajardo", email="jgajardo@gmail.com" },
]
description = "jipam libs para conectar a influxdb v1"
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/jgajardog/jipamlib_influxdb_v1"
