[tool.poetry]
name = "web3-py-tools"
version = "0.0.4"
description = ""
authors = ["pydevel <ppydevel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
aiohttp = ">=3.7.4.post0"
eth-abi = ">=4.0.0"
eth-account-api = "^1.0.0"
eth-hash = ">=0.5.1"
eth-typing = ">=3.0.0"
eth-utils = ">=2.1.0"
hexbytes = ">=0.1.0 <0.4.0"
jsonschema = ">=4.0.0"
lru-dict = ">=1.1.6 <1.3.0"
protobuf = ">=4.21.6"
requests = ">=2.16.0"
typing-extensions = ">=4.0.1"
websockets = ">=10.0.0"
pyunormalize = ">=15.0.0"
web3 = ">=5.0.0"
colorlog = "6.8.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
