[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "famudy-data"
version = "0.0.6"
description = "<<<ENTER_DESCRIPTION>>>"
authors = [
    { name = "Tobias Kirschstein", email = "tobias.kirschstein@gmail.com" },
]
readme = "README.md"
license = { text = "Apache 2.0" }
requires-python = ">=3.8.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
# urls = { Documentation = "<<<ENTER_LINK_TO_DOCUMENTATION>>>" }
# Main dependencies
dependencies = [
    "open3d",
    "trimesh",
    "environs",
    "elias",
    "tyro",
    "dreifus",
    "pandas",
    "python-openctm",

    # For FLAME:
    "smplx",
    "numpy<=1.23.1",  # chumpy requires numpy < 1.23.1
    "chumpy"
]

[project.optional-dependencies]
# Development packages, install via <<<PROJECT_NAME>>>[dev]
dev = [
]

[project.scripts]
# E.g., ns-download-data = "scripts.downloads.download_data:entrypoint"

[tool.setuptools.packages.find]
where = ["src"]
include = ["famudy*"]  # Keep the '*', otherwise submodules are not found