[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/hash-tg"]

[project]
name = "hash_tg"
version = "0.0.1"
authors = [
    { name = "Pavel Sushko", email = "pavel_sushko@pm.me" }
]
description = "Telegram bot for performing various functions against hashes"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Other Audience",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Security :: Cryptography",
    "Topic :: Utilities"
]

[project.urls]
homepage = "https://github.com/Pavel-Sushko/hash-tg"
issues = "https://github.com/Pavel-Sushko/hash-tg/issues"