[tool.poetry]
name = "riskalphaindics"
version = "0.1.0a1"
description = "Trading indicators for RiskAlpha trading bots."
authors = ["Niclas Hummel <info@algoinvest.online>", "Gwang-Jin Kim <gwang.jin.kim.phd@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "*"
numpy  = "*"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
